#ifndef CPR_CPR_H
#define CPR_CPR_H

#include "api.h"
#include "auth.h"
#include "bearer.h"
#include "callback.h"
#include "connect_timeout.h"
#include "cookies.h"
#include "cprtypes.h"
#include "cprver.h"
#include "curl_container.h"
#include "curlholder.h"
#include "error.h"
#include "http_version.h"
#include "interceptor.h"
#include "interface.h"
#include "limit_rate.h"
#include "low_speed.h"
#include "multipart.h"
#include "parameters.h"
#include "payload.h"
#include "proxies.h"
#include "proxyauth.h"
#include "range.h"
#include "redirect.h"
#include "reserve_size.h"
#include "response.h"
#include "session.h"
#include "ssl_options.h"
#include "status_codes.h"
#include "timeout.h"
#include "unix_socket.h"
#include "user_agent.h"
#include "util.h"
#include "verbose.h"

#define CPR_LIBCURL_VERSION_NUM LIBCURL_VERSION_NUM

#endif
